-- Sequence MVT_BONS_VALIDE
CREATE SEQUENCE seq_MVT_BONS_VALIDE
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;


-- Creation de la table MVT_BONS_VALIDE
CREATE TABLE MVT_BONS_VALIDE
(
  NUMMVT  NUMBER,
  D_BONS  VARCHAR2(10 BYTE),
  NUMSEM  NUMBER,
  NBRSS   NUMBER,
  NBRSS0  NUMBER,
  NBRSS1  NUMBER,
  NBRSS2  NUMBER,
  MAN     NUMBER,
  MAN1    NUMBER,
  MAN2    NUMBER,
  MSM     NUMBER,
  MSM1    NUMBER,
  MSM2    NUMBER,
  MAD     NUMBER,
  MAD1    NUMBER,
  MAD2    NUMBER,
  TXPMIN  NUMBER,
  TXPMAX  NUMBER,
  TXAMIN  NUMBER,
  TXAMAX  NUMBER,
  TXMP    NUMBER,
  CONSTRAINT pk_mvt PRIMARY KEY (NUMMVT)
);

Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, TXMP) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 1, 4.42);
Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, TXMP) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 2, 5.41);
Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, TXMP) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 3, 6.57);
Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, TXMP) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 4, 8.68);
Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, TXMP) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 5, 10.36);
Insert into MVT_BONS_VALIDE   (NUMMVT, D_BONS, NUMSEM, MAN, MAN1, MAN2,     MSM1, MAD1) Values   (seq_MVT_BONS_VALIDE.nextval,'27/03/26', 6, 44, 44, 0, 147.24, 44);


-- Sequence MVT_BONS_VALIDE_HISTORIQUE
CREATE SEQUENCE seq_MVT_BONS_VALIDE_HISTORIQUE
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- CREATION DE LA TABLE MVT_BONS_VALIDE_HISTORIQUE
CREATE TABLE MVT_BONS_VALIDE_HISTORIQUE
(
    ID NUMBER,
    MVT_BONS_VALIDE_ID  NUMBER NOT NULL,
    DATE_MODIFICATION   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIE_PAR         VARCHAR2(255 BYTE) DEFAULT NULL,
    CONSTRAINT pk_mvt_historique PRIMARY KEY (ID),
    CONSTRAINT fk_mvt_historique FOREIGN KEY (MVT_BONS_VALIDE_ID) REFERENCES MVT_BONS_VALIDE(NUMMVT) ON DELETE CASCADE  
);