CREATE TABLE BONS_VALIDE
(
  DDONS   DATE,
  VALEUR  NUMBER
);


CREATE TABLE MVT_BONS_VALIDE
(
  NUMMVT  NUMBER,
  D_BONS  VARCHAR2(10 BYTE),
  NUMSEM  NUMBER,
  NBRSS   NUMBER,
  NBRSS0  NUMBER,
  NBRSS1  NUMBER,
  NBRSS2  NUMBER,
  MAN     NUMBER,
  MAN1    NUMBER,
  MAN2    NUMBER,
  MSM     NUMBER,
  MSM1    NUMBER,
  MSM2    NUMBER,
  MAD     NUMBER,
  MAD1    NUMBER,
  MAD2    NUMBER,
  TXPMIN  NUMBER,
  TXPMAX  NUMBER,
  TXAMIN  NUMBER,
  TXAMAX  NUMBER,
  TXMP    NUMBER
);


