CREATE TABLE USER_AUTORIZED
(
  ID            NUMBER(10)                      NOT NULL,
  MATRICULE     VARCHAR2(10 CHAR),
  NOM           VARCHAR2(255 CHAR),
  IS_AUTORIZED  NUMBER(1)
);




CREATE TABLE ORIGINE_VALIDE
(
  ID          NUMBER(10)                        NOT NULL,
  ANNEE       VARCHAR2(10 BYTE)                 NOT NULL,
  NUMMOIS     VARCHAR2(10 BYTE)                 NOT NULL,
  ENSEMBLE    VARCHAR2(20 BYTE)                 NOT NULL,
  PRODLOCAL   VARCHAR2(30 BYTE)                 NOT NULL,
  PRODSEMIMP  VARCHAR2(30 BYTE)                 NOT NULL,
  PRODIMPORT  VARCHAR2(30 BYTE)                 NOT NULL,
  DELETED_AT  VARCHAR2(19 BYTE)                 DEFAULT NULL,
  CREATED_BY  VARCHAR2(255 BYTE)                DEFAULT NULL,
  UPDATED_AT  VARCHAR2(19 BYTE)                 DEFAULT NULL,
  CREATED_AT  VARCHAR2(19 BYTE)                 NOT NULL
);

CREATE TABLE ORIGINE_VALIDE_HISTORIQUE
(
  ID                 NUMBER(10)                 NOT NULL,
  ORIGINE_VALIDE_ID  NUMBER(10)                 NOT NULL,
  DATE_MODIFICATION  VARCHAR2(19 BYTE)          NOT NULL,
  MODIFIE_PAR        VARCHAR2(255 BYTE)         DEFAULT NULL
);

CREATE TABLE SECTEUR_VALIDE
(
  ID                NUMBER(10)                  NOT NULL,
  ANNEE             VARCHAR2(10 BYTE)           NOT NULL,
  NUMMOIS           VARCHAR2(10 BYTE)           NOT NULL,
  ENSEMBLE          VARCHAR2(20 BYTE)           NOT NULL,
  PRODVIVR_N_T      VARCHAR2(20 BYTE)           NOT NULL,
  PRODVIVR_T_N_RIZ  VARCHAR2(20 BYTE)           NOT NULL,
  PRODVIVR_T_RIZ    VARCHAR2(20 BYTE)           NOT NULL,
  PRODMANUFIND      VARCHAR2(20 BYTE)           NOT NULL,
  PRODMANUFART      VARCHAR2(20 BYTE)           NOT NULL,
  SERVPUBL          VARCHAR2(20 BYTE)           NOT NULL,
  SERVPRIV          VARCHAR2(20 BYTE)           NOT NULL,
  PPN               VARCHAR2(20 BYTE)           NOT NULL,
  DELETED_AT        VARCHAR2(255 CHAR)          DEFAULT NULL,
  CREATED_AT        VARCHAR2(255 CHAR)          NOT NULL,
  UPDATED_AT        VARCHAR2(255 CHAR)          DEFAULT NULL,
  CREATED_BY        VARCHAR2(255 BYTE)          DEFAULT NULL
);

CREATE TABLE SECTEUR_VALIDE_HISTORIQUE
(
  ID                 NUMBER(10)                 NOT NULL,
  SECTEUR_VALIDE_ID  NUMBER(10)                 NOT NULL,
  DATE_MODIFICATION  VARCHAR2(255 CHAR)         NOT NULL,
  MODIFIE_PAR        VARCHAR2(255 BYTE)         DEFAULT NULL
);


CREATE TABLE FONCTION_VALIDE
(
  ID                   NUMBER(10)               NOT NULL,
  ANNEE                VARCHAR2(255 BYTE)       NOT NULL,
  NUMMOIS              VARCHAR2(255 BYTE)       NOT NULL,
  ENSEMBLE             VARCHAR2(255 BYTE)       NOT NULL,
  PROD_ALIM_BOIS_NALC  VARCHAR2(255 BYTE)       NOT NULL,
  TISSU_VETEMENT       VARCHAR2(255 BYTE)       NOT NULL,
  LOGT_ET_COMBUST      VARCHAR2(255 BYTE)       NOT NULL,
  AM_EQMENA_ENTC_M     VARCHAR2(255 BYTE)       NOT NULL,
  SANTE                VARCHAR2(255 BYTE)       NOT NULL,
  TRANSPORTS           VARCHAR2(255 BYTE)       NOT NULL,
  LOISIR_SPECT_CULT    VARCHAR2(255 BYTE)       NOT NULL,
  ENSEIGNEMENT         VARCHAR2(255 BYTE)       NOT NULL,
  HOTEL_CAFE_REST      VARCHAR2(255 BYTE)       NOT NULL,
  AUTRES_BIEN_SERV     VARCHAR2(255 BYTE)       NOT NULL,
  BOIS_ALC_TAB         VARCHAR2(255 BYTE)       NOT NULL,
  COMMUNICATIONS       VARCHAR2(255 BYTE)       NOT NULL,
  DELETED_AT           VARCHAR2(19 BYTE)        DEFAULT NULL,
  CREATED_AT           VARCHAR2(19 BYTE)        NOT NULL,
  UPDATED_AT           VARCHAR2(19 BYTE)        DEFAULT NULL,
  CREATED_BY           VARCHAR2(255 BYTE)       DEFAULT NULL
);

CREATE TABLE FONCTION_VALIDE_HISTORIQUE
(
  ID                  NUMBER(10)                NOT NULL,
  FONCTION_VALIDE_ID  NUMBER(10)                NOT NULL,
  DATE_MODIFICATION   VARCHAR2(19 BYTE)         NOT NULL,
  MODIFIE_PAR         VARCHAR2(255 BYTE)        DEFAULT NULL
);


